### ISSUE TITLE
Forbid mutable defaults

### ISSUE THREAD

**Issue by sobolevn** [kalekseev/django-extra-checks#11]
For example, some people might use `JSONField(default={})`. Which is wrong. It should be `JSONField(default=dict)`.

**Comment by kalekseev** [comment]
JSONField covered by [postgres.E003](https://docs.djangoproject.com/en/3.1/ref/checks/#postgres), and starting from 3.1 it's covered by [fields.E010](https://docs.djangoproject.com/en/3.1/ref/checks/#model-fields)
