### ISSUE TITLE
Validate choices in database

### ISSUE THREAD

**Issue by kalekseev** [kalekseev/django-extra-checks#16]
Proposed by @hakib https://twitter.com/be_haki/status/1335797495176318977
Original idea by @bmispelon https://gist.github.com/bmispelon/93ea2abde9e57201a6bdcd85d0219a43
Downsides: need db connection, probably too expensive to run on each runserver reload.

**Comment by kalekseev** [comment]
Another check could enforce CheckConstraint on all choice fields as described by @adamchainz https://adamj.eu/tech/2020/01/22/djangos-field-choices-dont-constrain-your-data/

**Comment by adamchainz** [comment]
👍  Validating the check constraints exist will be easy and fast.

Scanning the DB to check data matches `choices` is too slow for a check once you have any scale.
