### ISSUE TITLE
Allow checks to apply only to 'local' apps

### ISSUE THREAD

**Issue by jayvdb** [kalekseev/django-extra-checks#2]
It would be nice to be able to easily (bool) flag that (all of/each of?) the checks only apply to apps that are within the (relative to..) project root.

**Comment by kalekseev** [comment]
Can you provide more information about your setup? Third party apps shouldn't be checked at all (you can't fix them anyway).
The code that filter out site packages: https://github.com/kalekseev/django-extra-checks/blob/2c64d69618169c8b42704d209461aa361b5640fc/src/extra_checks/controller.py#L124-L127

For example in my setup for this project it looks like this:
```
>>> import site
>>> site.PREFIXES
['/Users/kalekseev/projects/django-extra-checks/.direnv/python-3.8.2']
```
so all third party apps filtered out because they are placed inside this directory while project apps have path like `/Users/kalekseev/projects/django-extra-checks/tests/example`

**Comment by jayvdb** [comment]
Ok, that is actually very nice.  I wish most apps used that type of approach. (and I am going to steal that approach for django-dunders)

But ... now it gets trickier.

The problem in https://github.com/kalekseev/django-extra-checks/issues/1 was django-oscar, and its swappable models.

Now I have a local fork of several of their apps, including the one which triggered it.  My forked models inherit from the core abstract models they provide, and I add fields, and I dont want to be redefining the fields they provide.  So the checks should be activated at a field level if there is inheritance from a non-local app.

Also related, I think it would be a good idea to expose this local/non-local thing more clearly, say with
```py
EXTRA_CHECKS = {
    'local-app-checks': {..},
    'all-app-checks': {..},
}
```

Projects which use a lot of installable apps from third-parties would still want to have extra checks run on them, as a way of easily detecting bad quality apps, so the developer can use that info when considering whether they should integrate it, or find a better app, or build their own.

**Comment by kalekseev** [comment]
I added one more option to config `include_apps` https://github.com/kalekseev/django-extra-checks/commit/65411ecc6e6bd2abb94257970deb96203dd5e197
With that option you can specify what apps exactly you would like to check even third party apps.

> Projects which use a lot of installable apps from third-parties would still want to have extra checks run on them, as a way of easily detecting bad quality apps, so the developer can use that info when considering whether they should integrate it, or find a better app, or build their own.

Such scenario can be covered with some env variable, eg:

```
if os.environ.get('EXTRA_CHECKS_ALL_APPS'):
    EXTRA_CHECKS = {'include_apps': INSTALLED_APPS, ...}
else:
    EXTRA_CHECKS = ...
```
So when you want to check all apps you run `EXTRA_CHECKS_ALL_APPS=1 ./manage.py check`.

Please test if it cover your use cases, you can install master with `pip install  https://github.com/kalekseev/django-extra-checks/archive/master.tar.gz`

**Comment by jayvdb** [comment]
Perfect! Thanks
