### ISSUE TITLE
Configure checks per app (or using filters)

### ISSUE THREAD

**Issue by am0s** [kalekseev/django-extra-checks#22]
Is there a way to configure checks to only be applied to models from a specific Django app?
There are certain checks that I would like to only occur for one of my Django apps.

Basically I would like to do something like this, where *model-admin* checks only happen for the *main_app*

```python
EXTRA_CHECKS = {
    "checks": [
        "field-text-null",
        {"id": "model-admin", "filter": "main_app.*"},
    ]
}
```

It would be nice if filter could match app names and model names, maybe even having a list of filter strings?

**Comment by kalekseev** [comment]
@am0s released v0.10.0 that supports provides skipif options that should work for you:

```
def skipif_non_core_app(model_cls, *args, **kwargs):
    return model_cls._meta.app_label != "my_core_app"

EXTRA_CHECKS = {
    "check": [
        {
            "id": "model-admin",
            # models from non core app shouldn't be registered in admin
            "skipif": skipif_non_core_app,
        },
    ]
}
```
