### ISSUE TITLE
check-migration-names

### ISSUE THREAD

**Issue by mazlum** [kalekseev/django-extra-checks#28]
We can add check_migration_names from @adamchainz

Blog post:
https://adamj.eu/tech/2020/02/24/how-to-disallow-auto-named-django-migrations/#a-custom-system-check

**Comment by adamchainz** [comment]
There's no need - Django 4.0+ never generates migration names like 'auto_...' since https://code.djangoproject.com/ticket/31516 . I need to update that post with a banner.

**Comment by mazlum** [comment]
Thank you for your information.
