### ISSUE TITLE
Special characters throw field-verbose-name-gettext-case

### ISSUE THREAD

**Issue by kytta** [kalekseev/django-extra-checks#32]
If a `verbose_name` contains special characters, they fail the `islower()` / `isupper()` / `isdigit()` check defined here:

https://github.com/kalekseev/django-extra-checks/blob/07eb62d3dc92431c43ec21f2b6da56946b2a8b52/src/extra_checks/checks/model_field_checks.py#L102-L104

In my particular example, this field throws the `field-verbose-name-gettext-case` error:

```py
class Order(models.Model):
    details = models.TextField(
        _("order details / item list"),
    )
```

Perhaps adding the `islower()` check for the whole sentence will help?

```diff
            if (
                value
                and isinstance(value, str)
-                and not all(
+                and not (value.islower() or all(
                    w.islower() or w.isupper() or w.isdigit() for w in value.split(" ")
-                )
+                ))
            ):
                yield self.message(
                    "Words in verbose name must be all upper case or all lower case.",
                    hint=f'Change verbose name to "{value.lower()}".',
                    obj=field,
                )
```

**Comment by kalekseev** [comment]
Thank you for the report, fix released.

> Perhaps adding the islower() check for the whole sentence will help?

Text like "abc / XYZ" is valid but won't pass this check.

**Comment by kytta** [comment]
> Thank you for the report, fix released.

Thank you very much! That was quick 👍🏻

> > Perhaps adding the islower() check for the whole sentence will help?
> 
> Text like "abc / XYZ" is valid but won't pass this check.

Yeah that's why I OR'ed it with the old check and put the NOT over the brackets. This way, if the whole string is lowercase with special characters, it will work for the first half of the OR, otherwise the second half would be initiated. In any case, I find your fix much cleaner, so it doesn't matter 😅
