### ISSUE TITLE
get_latest_by

### ISSUE THREAD

**Issue by jayvdb** [kalekseev/django-extra-checks#8]
Often `get_latest_by` isnt set on models.  It would be useful to have a check for this for all models, esp if there is a date field on the model.

**Comment by kalekseev** [comment]
@jayvdb you can enforce that on all models with **model-meta-attribute** rule, add this to settings: `{"id": "model-meta-attribute", "attrs": ["get_latest_by"]}`. Enforcing it on models with date fields only will require separate rule, I'm not sure is it worth it.

**Comment by jayvdb** [comment]
I think it is only exposed in queryset `.earliest()` and `.latest()`, so I guess it isnt very important.
I use it with https://github.com/morlandi/django-tables-cleaner

Anyways, I try using `model-meta-attribute` and excludes for models which have nothing to order by.

**Comment by jayvdb** [comment]
Other apps I've found which use it:
- django_mock_queries
- queryset_sequence

**Comment by kalekseev** [comment]
`model-meta-attribute` is the way to go, no extra support is expected for that use case

**Comment by kalekseev** [comment]
@jayvdb check the latest version, you can provide your own skipif function to check only models that contain DateTime field in it, see test for example https://github.com/kalekseev/django-extra-checks/blob/a3c196825d636320b29b84c2d1e896fea1dc377c/tests/test_ignore.py#L123-L146

**Comment by jayvdb** [comment]
Very nice!
