### ISSUE TITLE
Reasoning behind `field-boolean-null`

### ISSUE THREAD

**Issue by sobolevn** [kalekseev/django-extra-checks#9]
I am wondering why do you recommend `BooleanField` instead of `NullBooleanField`?
I was always recommending `NullBooleanField` 🙂

**Comment by kalekseev** [comment]
It was 
> likely to be deprecated in a future version of Django

since version 2.1 https://docs.djangoproject.com/en/2.1/ref/models/fields/#nullbooleanfield 
and in version 3.1 finally became deprecated https://docs.djangoproject.com/en/3.1/ref/models/fields/#nullbooleanfield.
I should document that now the check make sense only for django<3.1.

**Comment by sobolevn** [comment]
Oh, thanks! I guess that it will be helpful for new users to have 'reasoning' section for all checks.
It could possibly teach a lot of people something good! 👍

**Comment by kalekseev** [comment]
> Oh, thanks! I guess that it will be helpful for new users to have 'reasoning' section for all checks.
> It could possibly teach a lot of people something good!

If only I had time :stuck_out_tongue_winking_eye:
